; Code generated by Cosmolang Architecture Research Labs. (CARL) v0.0.1.103-B
global _start
_start:
	mov rax, 1
	push rax
	mov rax, 2
	push rax
	mov rax, 3
	push rax
	; Add
	pop rax
	pop rbx
	add rax, rbx
	push rax
	; Add
	pop rax
	pop rbx
	add rax, rbx
	push rax
	mov rax, 1
	push rax
	mov rax, 2
	push rax
	; Call var: x
	push QWORD [rsp + 16]

	; Add
	pop rax
	pop rbx
	add rax, rbx
	push rax
	; Add
	pop rax
	pop rbx
	add rax, rbx
	push rax
	; Call var: y
	push QWORD [rsp + 0]

	; Exit by var.
	mov rax, 60
	pop rdi
	syscall
	mov rax, 60
	mov rdi, 0
	syscall
